wp-gatsby.php

as per the e-mail I sent you @TylerBarnes and @jasonbahl , here is my PR.
As I understand it, [the check for `WPGATSBY_AUTOLOAD` in `init()`](https://github.com/gatsbyjs/wp-gatsby/blob/master/wp-gatsby.php#L45) isn't needed because we need to [include `access-functions.php`](https://github.com/gatsbyjs/wp-gatsby/blob/master/wp-gatsby.php#L153) even when `WPGATSBY_AUTOLOAD` is set to `false`. The [check for `WPGATSBY_AUTOLOAD` inside `includes()`](https://github.com/gatsbyjs/wp-gatsby/blob/master/wp-gatsby.php#L147) is enough.
Currently, setting `WPGATSBY_AUTOLOAD` to `false` doesn't load this plugin correctly and `isWpGatsby` isn't added to the schema for example.

remove autoload check in init

---

src/ActionMonitor/ActionMonitor.php

This is a super simple solution for #22. 
Feel free to rename the filter to whatever makes the most sense. Not sure if you'd rather it be a `wp_gatsby` prefix.
I also thought about switching it to use `wp_safe_remote_request()`, to make it clearer that it could support sending a `GET` if that was required for some reason. But if someone forgot to merge the arguments when applying the filter or specify the method, then they would end up accidentally sending a `GET` request. 
The request method can still be overridden if it's passed in the arguments of `wp_safe_remote_post()`.

Add trigger dispatch filter

---

src/ActionMonitor/ActionMonitor.php

Closes #5 
This updates the post type registry for the Action Monitor post type to:
- not show in search
- not show in the REST API
- not show in nav menus

#5 - adjust the post type registry to not show in REST, not show in nav menus, etc

---

src/Admin/Settings.php

This filters the settings field and the value returned by `get_graphql_setting()` for the `public_introspection_enabled` setting to always be enabled as long as WPGatsby is active. 
_**Note:** The filters this hooks into are introduced to WPGraphQL in the [v0.14.0](https://github.com/wp-graphql/wp-graphql/pull/1513) release. So if you're on WPGraphQL v0.13.* you will need to manually check the setting to enable introspection when using WPGraphQL with Gatsby Source WordPress Experimental._
Introspection is _not_ enabled (but can be with the checkbox).
Here you can see GraphQL Playground cannot fetch the Schema but is provided an error saying that GraphQL Introspection is not allowed.
Introspection is checked and the setting is disabled so users cannot change it, and a message is added to …

#47 - force enable WPGraphQL Introspection

---

src/ActionMonitor/ActionMonitor.php
src/Admin/Preview.php

Don't send previews for published posts, instead use the regular save post webhook logic to post to the preview instance.

fix: disable polling in previews

---

CHANGELOG.md
readme.txt
src/ActionMonitor/ActionMonitor.php
wp-gatsby.php

Version 0.7.0 introduced a change which resulted in Previews for some WP instances being overwritten by published posts on each preview.

fix: previews

---

.github/workflows/create-source-plugin-pr.yml
.github/workflows/source-plugin-ci.yml

the actual issue with the workflow was a missing `/repos` path prefix in the request action
however, I just decided to use curl anyways, because of better error reporting, and because i could just copy the working curl from insomnia and replace with env vars and call it a day! haha

ci: use curl, add missing path prefix

---

src/Admin/Settings.php

Pointing link to the new docs link now that gatsby-source-wordpress is at 4.0.x

Updating Docs Link

---

src/ActionMonitor/Monitors/Monitor.php

Where the confusion comes from: `@param` is for the parameter name (not the value) which are non-existent in this case.

Fix gatsby_pre_log_action_monitor_action docblock

---

CHANGELOG.md
src/ActionMonitor/ActionMonitor.php

Before using WPGraphQL::debug() we weren't making sure that the debug method exists on that class. This could throw errors for older versions of WPGraphQL - we now check that the method exists before using it.

fix: Make sure the debug method exists before using it

---

src/Admin/Preview.php

Double slashes in the page-data.json request url work in `gatsby develop` but since PINC serves static files a double slash will return a 404. For example `frontendurl.com/page-data/foo//bar/page-data.json` works in old preview but breaks in PINC. It needs to be `frontendurl.com/page-data/foo/bar/page-data.json` to succeed. This PR ensures there won't be double slashes in the url.

fix(preview): Prevent double slashes in page-data.json request so PINC routing works

---

src/ActionMonitor/Monitors/PreviewMonitor.php

Currently opening a preview on a draft doesn't result in a preview because the preview logic is returning early for drafts. For now it seems the only way to get around this is to trigger previews for all drafts.

fix: trigger previews for drafts

---

src/Admin/Preview.php

This PR changes out preview status query so the preview loader can display an error if the Gatsby instance is configured to source data from a different WP instance.
related: https://github.com/gatsbyjs/gatsby/pull/32251

fix: Display error in browser when users preview on the wrong gatsby site

---

src/ActionMonitor/ActionMonitor.php

Preview webhooks added the remote url as a property on the webhook body. When publishing updates we also send a preview webhook to update the preview Gatsby site. These two webhook bodies previously differed in that the latter didn't include a remoteUrl property. As of `gatsby-source-wordpress@5.10.0` this causes problems because the source plugin assumes this property always exists. Related to https://github.com/gatsbyjs/gatsby/issues/32732

fix: add the remote url to all preview webhook bodies

---

src/ActionMonitor/ActionMonitor.php

WPGraphQL made a breaking change in a minor release `v1.6.7` which caused delta updates to stop working. This PR fixes that.
Related to https://github.com/wp-graphql/wp-graphql/issues/2142 and https://github.com/gatsbyjs/gatsby/discussions/33856
Closes https://github.com/gatsbyjs/wp-gatsby/issues/200

fix: Set publicly_queryable for WPGraphQL 1.6.7+

---

docs/action-monitor.md
src/ActionMonitor/ActionMonitor.php

Per the conversation in #174 , the following PR adds the `\WPGatsby\ActionMonitor\ActionMonitor` instance to the `gatsby_action_monitors` hook, in order to reintroduce the ability to register custom action monitors.
The PR adopts @alevgal 's [solution](https://github.com/gatsbyjs/wp-gatsby/issues/174#issuecomment-853851266). This method was chosen as it is an isolated (non-breaking) change that has no other effects on the existing codebase.
The only "downside" of this approach is that action monitors cannot be extended using the functional method referenced in the docs pre-commit. However, that isn't currently possible anyway (and would likely require a breaking change to imlement).
```php
/**
* Class - MyCustomActionMonitor
*/
class MyCustomActionMonitor extends …
```

fix: pass ActionMonitor instance to `gatsby_action_monitors` filter

---

src/ActionMonitor/ActionMonitor.php

This makes the action monitor sinceTimeStamp gql arg work properly when the local timezone is not UTC+0.

fix: use gmdate and post_modified_gmt to prevent using local timezone

---

CHANGELOG.md
src/Admin/Preview.php

This adds eager redirects support for Content Sync. 
This shouldn't be merged until Gatsby Cloud supports eager redirects.

feat: Add eager redirects support

---

src/ActionMonitor/Monitors/AcfMonitor.php
src/Utils/Utils.php

Possible related issues: #114, #174, #183, #181
This PR approaches the problem of ACF Option pages not triggering content updates in Gatsby if the options are "saved/updated".
As per suggestion of @TylerBarnes, `trigger_non_node_root_field_update` is used to update the option fields. By default this implementation would apply monitoring for all ACF registered option pages, but makes sure that it is only applied on those and not on normal post types to prevent triggering multiple content updates.
With the filter in place one can whitelist specific pages for monitoring or turn of monitoring by passing an empty array (or false).
```
add_filter('gatsby_action_monitor_tracked_acf_options_pages', function () {
return ['my-custom-option-page'];
});
```

ACF Options Page Monitoring

---

src/ActionMonitor/Monitors/AcfMonitor.php

fix: return early if acf options page fn isn't defined

---

CHANGELOG.md
src/ActionMonitor/ActionMonitor.php
src/ActionMonitor/Monitors/SettingsMonitor.php

Previously Author and Contributor roles couldn't properly use Gatsby Cloud Preview (it just wouldn't work). This PR introduces new custom role capabilities which allow all authenticated users that can use WP preview to use Gatsby Preview.

fix: preview for all roles

---

src/ActionMonitor/ActionMonitor.php
tests/wpunit/ActionMonitorTest.php

Fixes #202 so that CPTs with `'public' => false` and `'publicly_queryable' => true` trigger Action Monitor actions.

Track publicly_queryable post types
